### ISSUE TITLE
Extract Top 3 Things, PROMs and Feeds to a separate repository under https://github.com/pulsetile-plugins account

### ISSUE THREAD

**Issue by kbeloborodko** [LeedsCC/PulseTile-React#7] opened 2018-05-16 16:01 UTC

**Comment by tony-shannon** [comment] 2018-05-28 14:14
Duplicate of issue in the Master fork
please follow the related issue there
https://github.com/PulseTile/PulseTile-React/issues/143

**Closed by tony-shannon** 2018-05-28 14:14 UTC
